#ifndef GUARD_CONSTANTS_DUMMY_MAP_DEFINES_H
#define GUARD_CONSTANTS_DUMMY_MAP_DEFINES_H


// Required Maps
#define MAP_PETALBURG_CITY                                   28672
#define MAP_SLATEPORT_CITY                                   28673
#define MAP_MAUVILLE_CITY                                    28674
#define MAP_RUSTBORO_CITY                                    28675
#define MAP_FORTREE_CITY                                     28676
#define MAP_LILYCOVE_CITY                                    28677
#define MAP_MOSSDEEP_CITY                                    28678
#define MAP_SOOTOPOLIS_CITY                                  28679
#define MAP_EVER_GRANDE_CITY                                 28680
#define MAP_LITTLEROOT_TOWN                                  28681
#define MAP_OLDALE_TOWN                                      28682
#define MAP_DEWFORD_TOWN                                     28683
#define MAP_LAVARIDGE_TOWN                                   28684
#define MAP_FALLARBOR_TOWN                                   28685
#define MAP_VERDANTURF_TOWN                                  28686
#define MAP_PACIFIDLOG_TOWN                                  28687
#define MAP_ROUTE101                                         28688
#define MAP_ROUTE102                                         28689
#define MAP_ROUTE103                                         28690
#define MAP_ROUTE104                                         28691
#define MAP_ROUTE105                                         28692
#define MAP_ROUTE106                                         28693
#define MAP_ROUTE107                                         28694
#define MAP_ROUTE108                                         28695
#define MAP_ROUTE109                                         28696
#define MAP_ROUTE110                                         28697
#define MAP_ROUTE111                                         28698
#define MAP_ROUTE112                                         28699
#define MAP_ROUTE113                                         28700
#define MAP_ROUTE114                                         28701
#define MAP_ROUTE115                                         28702
#define MAP_ROUTE116                                         28703
#define MAP_ROUTE117                                         28704
#define MAP_ROUTE118                                         28705
#define MAP_ROUTE119                                         28706
#define MAP_ROUTE120                                         28707
#define MAP_ROUTE121                                         28708
#define MAP_ROUTE122                                         28709
#define MAP_ROUTE123                                         28710
#define MAP_ROUTE124                                         28711
#define MAP_ROUTE125                                         28712
#define MAP_ROUTE126                                         28713
#define MAP_ROUTE127                                         28714
#define MAP_ROUTE128                                         28715
#define MAP_ROUTE129                                         28716
#define MAP_ROUTE130                                         28717
#define MAP_ROUTE131                                         28718
#define MAP_ROUTE132                                         28719
#define MAP_ROUTE133                                         28720
#define MAP_ROUTE134                                         28721
#define MAP_UNDERWATER_ROUTE124                              28722
#define MAP_UNDERWATER_ROUTE126                              28723
#define MAP_UNDERWATER_ROUTE127                              28724
#define MAP_UNDERWATER_ROUTE128                              28725
#define MAP_UNDERWATER_ROUTE129                              28726
#define MAP_UNDERWATER_ROUTE105                              28727
#define MAP_UNDERWATER_ROUTE125                              28728
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F                28729
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F                28730
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F                    28731
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F                    28732
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB             28733
#define MAP_OLDALE_TOWN_HOUSE1                               28734
#define MAP_OLDALE_TOWN_HOUSE2                               28735
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F                    28736
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F                    28737
#define MAP_OLDALE_TOWN_MART                                 28738
#define MAP_DEWFORD_TOWN_HOUSE1                              28739
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F                   28740
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F                   28741
#define MAP_DEWFORD_TOWN_GYM                                 28742
#define MAP_DEWFORD_TOWN_HALL                                28743
#define MAP_DEWFORD_TOWN_HOUSE2                              28744
#define MAP_LAVARIDGE_TOWN_HERB_SHOP                         28745
#define MAP_LAVARIDGE_TOWN_GYM_1F                            28746
#define MAP_LAVARIDGE_TOWN_GYM_B1F                           28747
#define MAP_LAVARIDGE_TOWN_HOUSE                             28748
#define MAP_LAVARIDGE_TOWN_MART                              28749
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F                 28750
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F                 28751
#define MAP_FALLARBOR_TOWN_MART                              28752
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY                 28753
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR              28754
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM           28755
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F                 28756
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F                 28757
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE                      28758
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE             28759
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY                28760
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR             28761
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM          28762
#define MAP_VERDANTURF_TOWN_MART                             28763
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F                28764
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F                28765
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE                     28766
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE          28767
#define MAP_VERDANTURF_TOWN_HOUSE                            28768
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F                28769
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F                28770
#define MAP_PACIFIDLOG_TOWN_HOUSE1                           28771
#define MAP_PACIFIDLOG_TOWN_HOUSE2                           28772
#define MAP_PACIFIDLOG_TOWN_HOUSE3                           28773
#define MAP_PACIFIDLOG_TOWN_HOUSE4                           28774
#define MAP_PACIFIDLOG_TOWN_HOUSE5                           28775
#define MAP_PETALBURG_CITY_WALLYS_HOUSE                      28776
#define MAP_PETALBURG_CITY_GYM                               28777
#define MAP_PETALBURG_CITY_HOUSE1                            28778
#define MAP_PETALBURG_CITY_HOUSE2                            28779
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F                 28780
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F                 28781
#define MAP_PETALBURG_CITY_MART                              28782
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F                28783
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F                28784
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY                 28785
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR              28786
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM           28787
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE                 28788
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB                  28789
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F                 28790
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F                 28791
#define MAP_SLATEPORT_CITY_HARBOR                            28792
#define MAP_SLATEPORT_CITY_HOUSE                             28793
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F                 28794
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F                 28795
#define MAP_SLATEPORT_CITY_MART                              28796
#define MAP_MAUVILLE_CITY_GYM                                28928
#define MAP_MAUVILLE_CITY_BIKE_SHOP                          28929
#define MAP_MAUVILLE_CITY_HOUSE1                             28930
#define MAP_MAUVILLE_CITY_GAME_CORNER                        28931
#define MAP_MAUVILLE_CITY_HOUSE2                             28932
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F                  28933
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F                  28934
#define MAP_MAUVILLE_CITY_MART                               28935
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F                      28936
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F                      28937
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F                      28938
#define MAP_RUSTBORO_CITY_GYM                                28939
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL                     28940
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F                  28941
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F                  28942
#define MAP_RUSTBORO_CITY_MART                               28943
#define MAP_RUSTBORO_CITY_FLAT1_1F                           28944
#define MAP_RUSTBORO_CITY_FLAT1_2F                           28945
#define MAP_RUSTBORO_CITY_HOUSE1                             28946
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE                      28947
#define MAP_RUSTBORO_CITY_HOUSE2                             28948
#define MAP_RUSTBORO_CITY_FLAT2_1F                           28949
#define MAP_RUSTBORO_CITY_FLAT2_2F                           28950
#define MAP_RUSTBORO_CITY_FLAT2_3F                           28951
#define MAP_RUSTBORO_CITY_HOUSE3                             28952
#define MAP_FORTREE_CITY_HOUSE1                              28953
#define MAP_FORTREE_CITY_GYM                                 28954
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F                   28955
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F                   28956
#define MAP_FORTREE_CITY_MART                                28957
#define MAP_FORTREE_CITY_HOUSE2                              28958
#define MAP_FORTREE_CITY_HOUSE3                              28959
#define MAP_FORTREE_CITY_HOUSE4                              28960
#define MAP_FORTREE_CITY_HOUSE5                              28961
#define MAP_FORTREE_CITY_DECORATION_SHOP                     28962
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F                 28963
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F                 28964
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F                 28965
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F                 28966
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY                      28967
#define MAP_LILYCOVE_CITY_CONTEST_HALL                       28968
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F                  28969
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F                  28970
#define MAP_LILYCOVE_CITY_UNUSED_MART                        28971
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB           28972
#define MAP_LILYCOVE_CITY_HARBOR                             28973
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE                28974
#define MAP_LILYCOVE_CITY_HOUSE1                             28975
#define MAP_LILYCOVE_CITY_HOUSE2                             28976
#define MAP_LILYCOVE_CITY_HOUSE3                             28977
#define MAP_LILYCOVE_CITY_HOUSE4                             28978
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F                28979
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F                28980
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F                28981
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F                28982
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F                28983
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP           28984
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR          28985
#define MAP_MOSSDEEP_CITY_GYM                                28986
#define MAP_MOSSDEEP_CITY_HOUSE1                             28987
#define MAP_MOSSDEEP_CITY_HOUSE2                             28988
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F                  28989
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F                  28990
#define MAP_MOSSDEEP_CITY_MART                               28991
#define MAP_MOSSDEEP_CITY_HOUSE3                             28992
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE                      28993
#define MAP_MOSSDEEP_CITY_HOUSE4                             28994
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F                    28995
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F                    28996
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F                     28997
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F                    28998
#define MAP_SOOTOPOLIS_CITY_GYM_1F                           28999
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                          29000
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F                29001
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F                29002
#define MAP_SOOTOPOLIS_CITY_MART                             29003
#define MAP_SOOTOPOLIS_CITY_HOUSE1                           29004
#define MAP_SOOTOPOLIS_CITY_HOUSE2                           29005
#define MAP_SOOTOPOLIS_CITY_HOUSE3                           29006
#define MAP_SOOTOPOLIS_CITY_HOUSE4                           29007
#define MAP_SOOTOPOLIS_CITY_HOUSE5                           29008
#define MAP_SOOTOPOLIS_CITY_HOUSE6                           29009
#define MAP_SOOTOPOLIS_CITY_HOUSE7                           29010
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE           29011
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F          29012
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F         29013
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM                    29014
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM                    29015
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM                    29016
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM                     29017
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM                  29018
#define MAP_EVER_GRANDE_CITY_HALL1                           29019
#define MAP_EVER_GRANDE_CITY_HALL2                           29020
#define MAP_EVER_GRANDE_CITY_HALL3                           29021
#define MAP_EVER_GRANDE_CITY_HALL4                           29022
#define MAP_EVER_GRANDE_CITY_HALL5                           29023
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F               29024
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME                    29025
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F               29026
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F               29027
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F               29028
#define MAP_ROUTE104_MR_BRINEYS_HOUSE                        29029
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP                29030
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE                 29031
#define MAP_ROUTE111_OLD_LADYS_REST_STOP                     29032
#define MAP_ROUTE112_CABLE_CAR_STATION                       29033
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION                     29034
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE                    29035
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL                   29036
#define MAP_ROUTE114_LANETTES_HOUSE                          29037
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE                    29038
#define MAP_ROUTE117_POKEMON_DAY_CARE                        29039
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE                    29040
#define MAP_METEOR_FALLS_1F_1R                               29184
#define MAP_METEOR_FALLS_1F_2R                               29185
#define MAP_METEOR_FALLS_B1F_1R                              29186
#define MAP_METEOR_FALLS_B1F_2R                              29187
#define MAP_RUSTURF_TUNNEL                                   29188
#define MAP_UNDERWATER_SOOTOPOLIS_CITY                       29189
#define MAP_DESERT_RUINS                                     29190
#define MAP_GRANITE_CAVE_1F                                  29191
#define MAP_GRANITE_CAVE_B1F                                 29192
#define MAP_GRANITE_CAVE_B2F                                 29193
#define MAP_GRANITE_CAVE_STEVENS_ROOM                        29194
#define MAP_PETALBURG_WOODS                                  29195
#define MAP_MT_CHIMNEY                                       29196
#define MAP_JAGGED_PASS                                      29197
#define MAP_FIERY_PATH                                       29198
#define MAP_MT_PYRE_1F                                       29199
#define MAP_MT_PYRE_2F                                       29200
#define MAP_MT_PYRE_3F                                       29201
#define MAP_MT_PYRE_4F                                       29202
#define MAP_MT_PYRE_5F                                       29203
#define MAP_MT_PYRE_6F                                       29204
#define MAP_MT_PYRE_EXTERIOR                                 29205
#define MAP_MT_PYRE_SUMMIT                                   29206
#define MAP_AQUA_HIDEOUT_1F                                  29207
#define MAP_AQUA_HIDEOUT_B1F                                 29208
#define MAP_AQUA_HIDEOUT_B2F                                 29209
#define MAP_UNDERWATER_SEAFLOOR_CAVERN                       29210
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                         29211
#define MAP_SEAFLOOR_CAVERN_ROOM1                            29212
#define MAP_SEAFLOOR_CAVERN_ROOM2                            29213
#define MAP_SEAFLOOR_CAVERN_ROOM3                            29214
#define MAP_SEAFLOOR_CAVERN_ROOM4                            29215
#define MAP_SEAFLOOR_CAVERN_ROOM5                            29216
#define MAP_SEAFLOOR_CAVERN_ROOM6                            29217
#define MAP_SEAFLOOR_CAVERN_ROOM7                            29218
#define MAP_SEAFLOOR_CAVERN_ROOM8                            29219
#define MAP_SEAFLOOR_CAVERN_ROOM9                            29220
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                          29221
#define MAP_CAVE_OF_ORIGIN_1F                                29222
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1         29223
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2         29224
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3         29225
#define MAP_CAVE_OF_ORIGIN_B1F                               29226
#define MAP_VICTORY_ROAD_1F                                  29227
#define MAP_VICTORY_ROAD_B1F                                 29228
#define MAP_VICTORY_ROAD_B2F                                 29229
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM                29230
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM                   29231
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM                  29232
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM                   29233
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM               29234
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM                  29235
#define MAP_NEW_MAUVILLE_ENTRANCE                            29236
#define MAP_NEW_MAUVILLE_INSIDE                              29237
#define MAP_ABANDONED_SHIP_DECK                              29238
#define MAP_ABANDONED_SHIP_CORRIDORS_1F                      29239
#define MAP_ABANDONED_SHIP_ROOMS_1F                          29240
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F                     29241
#define MAP_ABANDONED_SHIP_ROOMS_B1F                         29242
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                        29243
#define MAP_ABANDONED_SHIP_UNDERWATER1                       29244
#define MAP_ABANDONED_SHIP_ROOM_B1F                          29245
#define MAP_ABANDONED_SHIP_ROOMS2_1F                         29246
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE                   29247
#define MAP_ABANDONED_SHIP_UNDERWATER2                       29248
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS            29249
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS                29250
#define MAP_ISLAND_CAVE                                      29251
#define MAP_ANCIENT_TOMB                                     29252
#define MAP_UNDERWATER_ROUTE134                              29253
#define MAP_UNDERWATER_SEALED_CHAMBER                        29254
#define MAP_SEALED_CHAMBER_OUTER_ROOM                        29255
#define MAP_SEALED_CHAMBER_INNER_ROOM                        29256
#define MAP_SCORCHED_SLAB                                    29257
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1                    29258
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2                    29259
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3                    29260
#define MAP_SKY_PILLAR_ENTRANCE                              29261
#define MAP_SKY_PILLAR_OUTSIDE                               29262
#define MAP_SKY_PILLAR_1F                                    29263
#define MAP_SKY_PILLAR_2F                                    29264
#define MAP_SKY_PILLAR_3F                                    29265
#define MAP_SKY_PILLAR_4F                                    29266
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM                     29267
#define MAP_SKY_PILLAR_5F                                    29268
#define MAP_SKY_PILLAR_TOP                                   29269
#define MAP_MAGMA_HIDEOUT_1F                                 29270
#define MAP_MAGMA_HIDEOUT_2F_1R                              29271
#define MAP_MAGMA_HIDEOUT_2F_2R                              29272
#define MAP_MAGMA_HIDEOUT_3F_1R                              29273
#define MAP_MAGMA_HIDEOUT_3F_2R                              29274
#define MAP_MAGMA_HIDEOUT_4F                                 29275
#define MAP_MAGMA_HIDEOUT_3F_3R                              29276
#define MAP_MAGMA_HIDEOUT_2F_3R                              29277
#define MAP_MIRAGE_TOWER_1F                                  29278
#define MAP_MIRAGE_TOWER_2F                                  29279
#define MAP_MIRAGE_TOWER_3F                                  29280
#define MAP_MIRAGE_TOWER_4F                                  29281
#define MAP_DESERT_UNDERPASS                                 29282
#define MAP_ARTISAN_CAVE_B1F                                 29283
#define MAP_ARTISAN_CAVE_1F                                  29284
#define MAP_UNDERWATER_MARINE_CAVE                           29285
#define MAP_MARINE_CAVE_ENTRANCE                             29286
#define MAP_MARINE_CAVE_END                                  29287
#define MAP_TERRA_CAVE_ENTRANCE                              29288
#define MAP_TERRA_CAVE_END                                   29289
#define MAP_ALTERING_CAVE                                    29290
#define MAP_METEOR_FALLS_STEVENS_CAVE                        29291
#define MAP_SECRET_BASE_RED_CAVE1                            29440
#define MAP_SECRET_BASE_BROWN_CAVE1                          29441
#define MAP_SECRET_BASE_BLUE_CAVE1                           29442
#define MAP_SECRET_BASE_YELLOW_CAVE1                         29443
#define MAP_SECRET_BASE_TREE1                                29444
#define MAP_SECRET_BASE_SHRUB1                               29445
#define MAP_SECRET_BASE_RED_CAVE2                            29446
#define MAP_SECRET_BASE_BROWN_CAVE2                          29447
#define MAP_SECRET_BASE_BLUE_CAVE2                           29448
#define MAP_SECRET_BASE_YELLOW_CAVE2                         29449
#define MAP_SECRET_BASE_TREE2                                29450
#define MAP_SECRET_BASE_SHRUB2                               29451
#define MAP_SECRET_BASE_RED_CAVE3                            29452
#define MAP_SECRET_BASE_BROWN_CAVE3                          29453
#define MAP_SECRET_BASE_BLUE_CAVE3                           29454
#define MAP_SECRET_BASE_YELLOW_CAVE3                         29455
#define MAP_SECRET_BASE_TREE3                                29456
#define MAP_SECRET_BASE_SHRUB3                               29457
#define MAP_SECRET_BASE_RED_CAVE4                            29458
#define MAP_SECRET_BASE_BROWN_CAVE4                          29459
#define MAP_SECRET_BASE_BLUE_CAVE4                           29460
#define MAP_SECRET_BASE_YELLOW_CAVE4                         29461
#define MAP_SECRET_BASE_TREE4                                29462
#define MAP_SECRET_BASE_SHRUB4                               29463
#define MAP_BATTLE_COLOSSEUM_2P                              29464
#define MAP_TRADE_CENTER                                     29465
#define MAP_RECORD_CORNER                                    29466
#define MAP_BATTLE_COLOSSEUM_4P                              29467
#define MAP_CONTEST_HALL                                     29468
#define MAP_UNUSED_CONTEST_HALL1                             29469
#define MAP_UNUSED_CONTEST_HALL2                             29470
#define MAP_UNUSED_CONTEST_HALL3                             29471
#define MAP_UNUSED_CONTEST_HALL4                             29472
#define MAP_UNUSED_CONTEST_HALL5                             29473
#define MAP_UNUSED_CONTEST_HALL6                             29474
#define MAP_CONTEST_HALL_BEAUTY                              29475
#define MAP_CONTEST_HALL_TOUGH                               29476
#define MAP_CONTEST_HALL_COOL                                29477
#define MAP_CONTEST_HALL_SMART                               29478
#define MAP_CONTEST_HALL_CUTE                                29479
#define MAP_INSIDE_OF_TRUCK                                  29480
#define MAP_SS_TIDAL_CORRIDOR                                29481
#define MAP_SS_TIDAL_LOWER_DECK                              29482
#define MAP_SS_TIDAL_ROOMS                                   29483
#define MAP_BATTLE_PYRAMID_SQUARE01                          29484
#define MAP_BATTLE_PYRAMID_SQUARE02                          29485
#define MAP_BATTLE_PYRAMID_SQUARE03                          29486
#define MAP_BATTLE_PYRAMID_SQUARE04                          29487
#define MAP_BATTLE_PYRAMID_SQUARE05                          29488
#define MAP_BATTLE_PYRAMID_SQUARE06                          29489
#define MAP_BATTLE_PYRAMID_SQUARE07                          29490
#define MAP_BATTLE_PYRAMID_SQUARE08                          29491
#define MAP_BATTLE_PYRAMID_SQUARE09                          29492
#define MAP_BATTLE_PYRAMID_SQUARE10                          29493
#define MAP_BATTLE_PYRAMID_SQUARE11                          29494
#define MAP_BATTLE_PYRAMID_SQUARE12                          29495
#define MAP_BATTLE_PYRAMID_SQUARE13                          29496
#define MAP_BATTLE_PYRAMID_SQUARE14                          29497
#define MAP_BATTLE_PYRAMID_SQUARE15                          29498
#define MAP_BATTLE_PYRAMID_SQUARE16                          29499
#define MAP_UNION_ROOM                                       29500
#define MAP_SAFARI_ZONE_NORTHWEST                            29696
#define MAP_SAFARI_ZONE_NORTH                                29697
#define MAP_SAFARI_ZONE_SOUTHWEST                            29698
#define MAP_SAFARI_ZONE_SOUTH                                29699
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                     29700
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY               29701
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR            29702
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR            29703
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM         29704
#define MAP_SOUTHERN_ISLAND_EXTERIOR                         29705
#define MAP_SOUTHERN_ISLAND_INTERIOR                         29706
#define MAP_SAFARI_ZONE_REST_HOUSE                           29707
#define MAP_SAFARI_ZONE_NORTHEAST                            29708
#define MAP_SAFARI_ZONE_SOUTHEAST                            29709
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                     29710
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM  29711
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR      29712
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM   29713
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY                29714
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR             29715
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM      29716
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM          29717
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY              29718
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR           29719
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM        29720
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY             29721
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR             29722
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP               29723
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY               29724
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR            29725
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM         29726
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY             29727
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM   29728
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM       29729
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY                29730
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR             29731
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM      29732
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL          29733
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL           29734
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS       29735
#define MAP_BATTLE_FRONTIER_RANKING_HALL                     29736
#define MAP_BATTLE_FRONTIER_LOUNGE1                          29737
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER          29738
#define MAP_BATTLE_FRONTIER_LOUNGE2                          29739
#define MAP_BATTLE_FRONTIER_LOUNGE3                          29740
#define MAP_BATTLE_FRONTIER_LOUNGE4                          29741
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                     29742
#define MAP_BATTLE_FRONTIER_LOUNGE5                          29743
#define MAP_BATTLE_FRONTIER_LOUNGE6                          29744
#define MAP_BATTLE_FRONTIER_LOUNGE7                          29745
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                   29746
#define MAP_BATTLE_FRONTIER_LOUNGE8                          29747
#define MAP_BATTLE_FRONTIER_LOUNGE9                          29748
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F                29749
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F                29750
#define MAP_BATTLE_FRONTIER_MART                             29751
#define MAP_FARAWAY_ISLAND_ENTRANCE                          29752
#define MAP_FARAWAY_ISLAND_INTERIOR                          29753
#define MAP_BIRTH_ISLAND_EXTERIOR                            29754
#define MAP_BIRTH_ISLAND_HARBOR                              29755
#define MAP_TRAINER_HILL_ENTRANCE                            29756
#define MAP_TRAINER_HILL_1F                                  29757
#define MAP_TRAINER_HILL_2F                                  29758
#define MAP_TRAINER_HILL_3F                                  29759
#define MAP_TRAINER_HILL_4F                                  29760
#define MAP_TRAINER_HILL_ROOF                                29761
#define MAP_NAVEL_ROCK_EXTERIOR                              29952
#define MAP_NAVEL_ROCK_HARBOR                                29953
#define MAP_NAVEL_ROCK_ENTRANCE                              29954
#define MAP_NAVEL_ROCK_B1F                                   29955
#define MAP_NAVEL_ROCK_FORK                                  29956
#define MAP_NAVEL_ROCK_UP1                                   29957
#define MAP_NAVEL_ROCK_UP2                                   29958
#define MAP_NAVEL_ROCK_UP3                                   29959
#define MAP_NAVEL_ROCK_UP4                                   29960
#define MAP_NAVEL_ROCK_TOP                                   29961
#define MAP_NAVEL_ROCK_DOWN01                                29962
#define MAP_NAVEL_ROCK_DOWN02                                29963
#define MAP_NAVEL_ROCK_DOWN03                                29964
#define MAP_NAVEL_ROCK_DOWN04                                29965
#define MAP_NAVEL_ROCK_DOWN05                                29966
#define MAP_NAVEL_ROCK_DOWN06                                29967
#define MAP_NAVEL_ROCK_DOWN07                                29968
#define MAP_NAVEL_ROCK_DOWN08                                29969
#define MAP_NAVEL_ROCK_DOWN09                                29970
#define MAP_NAVEL_ROCK_DOWN10                                29971
#define MAP_NAVEL_ROCK_DOWN11                                29972
#define MAP_NAVEL_ROCK_BOTTOM                                29973
#define MAP_TRAINER_HILL_ELEVATOR                            29974
#define MAP_ROUTE104_PROTOTYPE                               29975
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP      29976
#define MAP_ROUTE109_SEASHORE_HOUSE                          29977
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                    29978
#define MAP_ROUTE110_TRICK_HOUSE_END                         29979
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                    29980
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                     29981
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                     29982
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                     29983
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                     29984
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                     29985
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                     29986
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                     29987
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                     29988
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE     29989
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE     29990
#define MAP_ROUTE113_GLASS_WORKSHOP                          29991
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE                     29992
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F                    29993
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F                    29994
#define MAP_ROUTE119_HOUSE                                   29995
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE           29996
#define MAP_BATTLE_COLOSSEUM_2P_FRLG                         29997
#define MAP_TRADE_CENTER_FRLG                                29998
#define MAP_RECORD_CORNER_FRLG                               29999
#define MAP_BATTLE_COLOSSEUM_4P_FRLG                         30000
#define MAP_UNION_ROOM_FRLG                                  30001
#define MAP_SAFARI_ZONE_CENTER                               30208
#define MAP_SAFARI_ZONE_EAST                                 30209
#define MAP_SAFARI_ZONE_NORTH_FRLG                           30210
#define MAP_SAFARI_ZONE_WEST                                 30211
#define MAP_SAFARI_ZONE_CENTER_REST_HOUSE                    30212
#define MAP_SAFARI_ZONE_EAST_REST_HOUSE                      30213
#define MAP_SAFARI_ZONE_NORTH_REST_HOUSE                     30214
#define MAP_SAFARI_ZONE_WEST_REST_HOUSE                      30215
#define MAP_SAFARI_ZONE_SECRET_HOUSE                         30216
#define MAP_CERULEAN_CAVE_1F                                 30217
#define MAP_CERULEAN_CAVE_2F                                 30218
#define MAP_CERULEAN_CAVE_B1F                                30219
#define MAP_POKEMON_LEAGUE_LORELEIS_ROOM                     30220
#define MAP_POKEMON_LEAGUE_BRUNOS_ROOM                       30221
#define MAP_POKEMON_LEAGUE_AGATHAS_ROOM                      30222
#define MAP_POKEMON_LEAGUE_LANCES_ROOM                       30223
#define MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM                    30224
#define MAP_POKEMON_LEAGUE_HALL_OF_FAME                      30225
#define MAP_ROCK_TUNNEL_1F                                   30226
#define MAP_ROCK_TUNNEL_B1F                                  30227
#define MAP_SEAFOAM_ISLANDS_1F                               30228
#define MAP_SEAFOAM_ISLANDS_B1F                              30229
#define MAP_SEAFOAM_ISLANDS_B2F                              30230
#define MAP_SEAFOAM_ISLANDS_B3F                              30231
#define MAP_SEAFOAM_ISLANDS_B4F                              30232
#define MAP_POKEMON_TOWER_1F                                 30233
#define MAP_POKEMON_TOWER_2F                                 30234
#define MAP_POKEMON_TOWER_3F                                 30235
#define MAP_POKEMON_TOWER_4F                                 30236
#define MAP_POKEMON_TOWER_5F                                 30237
#define MAP_POKEMON_TOWER_6F                                 30238
#define MAP_POKEMON_TOWER_7F                                 30239
#define MAP_POWER_PLANT                                      30240
#define MAP_MT_EMBER_RUBY_PATH_B4F                           30241
#define MAP_MT_EMBER_EXTERIOR                                30242
#define MAP_MT_EMBER_SUMMIT_PATH_1F                          30243
#define MAP_MT_EMBER_SUMMIT_PATH_2F                          30244
#define MAP_MT_EMBER_SUMMIT_PATH_3F                          30245
#define MAP_MT_EMBER_SUMMIT                                  30246
#define MAP_MT_EMBER_RUBY_PATH_B5F                           30247
#define MAP_MT_EMBER_RUBY_PATH_1F                            30248
#define MAP_MT_EMBER_RUBY_PATH_B1F                           30249
#define MAP_MT_EMBER_RUBY_PATH_B2F                           30250
#define MAP_MT_EMBER_RUBY_PATH_B3F                           30251
#define MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS                    30252
#define MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS                    30253
#define MAP_THREE_ISLAND_BERRY_FOREST                        30254
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE                30255
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_1F                      30256
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F                     30257
#define MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK                    30258
#define MAP_FIVE_ISLAND_ROCKET_WAREHOUSE                     30259
#define MAP_SIX_ISLAND_DOTTED_HOLE_1F                        30260
#define MAP_SIX_ISLAND_DOTTED_HOLE_B1F                       30261
#define MAP_SIX_ISLAND_DOTTED_HOLE_B2F                       30262
#define MAP_SIX_ISLAND_DOTTED_HOLE_B3F                       30263
#define MAP_SIX_ISLAND_DOTTED_HOLE_B4F                       30264
#define MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM             30265
#define MAP_SIX_ISLAND_PATTERN_BUSH                          30266
#define MAP_SIX_ISLAND_ALTERING_CAVE                         30267
#define MAP_NAVEL_ROCK_EXTERIOR_FRLG                         30268
#define MAP_TRAINER_TOWER_1F                                 30269
#define MAP_TRAINER_TOWER_2F                                 30270
#define MAP_TRAINER_TOWER_3F                                 30271
#define MAP_TRAINER_TOWER_4F                                 30272
#define MAP_TRAINER_TOWER_5F                                 30273
#define MAP_TRAINER_TOWER_6F                                 30274
#define MAP_TRAINER_TOWER_7F                                 30275
#define MAP_TRAINER_TOWER_8F                                 30276
#define MAP_TRAINER_TOWER_ROOF                               30277
#define MAP_TRAINER_TOWER_LOBBY                              30278
#define MAP_TRAINER_TOWER_ELEVATOR                           30279
#define MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE                   30280
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM1                      30281
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM2                      30282
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM3                      30283
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM4                      30284
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM5                      30285
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM6                      30286
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM7                      30287
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM8                      30288
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM9                      30289
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM10                     30290
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM11                     30291
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM12                     30292
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM13                     30293
#define MAP_FIVE_ISLAND_LOST_CAVE_ROOM14                     30294
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER         30295
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER         30296
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER         30297
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER        30298
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER         30299
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER           30300
#define MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER        30301
#define MAP_THREE_ISLAND_DUNSPARCE_TUNNEL                    30302
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY           30303
#define MAP_NAVEL_ROCK_1F                                    30464
#define MAP_NAVEL_ROCK_SUMMIT                                30465
#define MAP_NAVEL_ROCK_BASE_FRLG                             30466
#define MAP_NAVEL_ROCK_SUMMIT_PATH_2F                        30467
#define MAP_NAVEL_ROCK_SUMMIT_PATH_3F                        30468
#define MAP_NAVEL_ROCK_SUMMIT_PATH_4F                        30469
#define MAP_NAVEL_ROCK_SUMMIT_PATH_5F                        30470
#define MAP_NAVEL_ROCK_BASE_PATH_B1F                         30471
#define MAP_NAVEL_ROCK_BASE_PATH_B2F                         30472
#define MAP_NAVEL_ROCK_BASE_PATH_B3F                         30473
#define MAP_NAVEL_ROCK_BASE_PATH_B4F                         30474
#define MAP_NAVEL_ROCK_BASE_PATH_B5F                         30475
#define MAP_NAVEL_ROCK_BASE_PATH_B6F                         30476
#define MAP_NAVEL_ROCK_BASE_PATH_B7F                         30477
#define MAP_NAVEL_ROCK_BASE_PATH_B8F                         30478
#define MAP_NAVEL_ROCK_BASE_PATH_B9F                         30479
#define MAP_NAVEL_ROCK_BASE_PATH_B10F                        30480
#define MAP_NAVEL_ROCK_BASE_PATH_B11F                        30481
#define MAP_NAVEL_ROCK_B1F_FRLG                              30482
#define MAP_NAVEL_ROCK_FORK_FRLG                             30483
#define MAP_BIRTH_ISLAND_EXTERIOR_FRLG                       30484
#define MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA                 30485
#define MAP_BIRTH_ISLAND_HARBOR_FRLG                         30486
#define MAP_NAVEL_ROCK_HARBOR_FRLG                           30487
#define MAP_PALLET_TOWN                                      30720
#define MAP_VIRIDIAN_CITY                                    30721
#define MAP_PEWTER_CITY                                      30722
#define MAP_CERULEAN_CITY                                    30723
#define MAP_LAVENDER_TOWN                                    30724
#define MAP_VERMILION_CITY                                   30725
#define MAP_CELADON_CITY                                     30726
#define MAP_FUCHSIA_CITY                                     30727
#define MAP_CINNABAR_ISLAND                                  30728
#define MAP_INDIGO_PLATEAU_EXTERIOR                          30729
#define MAP_SAFFRON_CITY                                     30730
#define MAP_SAFFRON_CITY_CONNECTION                          30731
#define MAP_ONE_ISLAND                                       30732
#define MAP_TWO_ISLAND                                       30733
#define MAP_THREE_ISLAND                                     30734
#define MAP_FOUR_ISLAND                                      30735
#define MAP_FIVE_ISLAND                                      30736
#define MAP_SEVEN_ISLAND                                     30737
#define MAP_SIX_ISLAND                                       30738
#define MAP_ROUTE7                                           30745
#define MAP_ROUTE8                                           30746
#define MAP_ROUTE9                                           30747
#define MAP_ROUTE10                                          30748
#define MAP_ROUTE13                                          30751
#define MAP_ROUTE14                                          30752
#define MAP_ROUTE21_NORTH                                    30759
#define MAP_ROUTE21_SOUTH                                    30760
#define MAP_ROUTE22                                          30761
#define MAP_ROUTE23                                          30762
#define MAP_ROUTE24                                          30763
#define MAP_ROUTE25                                          30764
#define MAP_ONE_ISLAND_KINDLE_ROAD                           30765
#define MAP_ONE_ISLAND_TREASURE_BEACH                        30766
#define MAP_TWO_ISLAND_CAPE_BRINK                            30767
#define MAP_THREE_ISLAND_BOND_BRIDGE                         30768
#define MAP_THREE_ISLAND_PORT                                30769
#define MAP_FIVE_ISLAND_RESORT_GORGEOUS                      30770
#define MAP_FIVE_ISLAND_WATER_LABYRINTH                      30771
#define MAP_FIVE_ISLAND_MEADOW                               30772
#define MAP_FIVE_ISLAND_MEMORIAL_PILLAR                      30773
#define MAP_SIX_ISLAND_OUTCAST_ISLAND                        30774
#define MAP_SIX_ISLAND_GREEN_PATH                            30775
#define MAP_SIX_ISLAND_WATER_PATH                            30776
#define MAP_SIX_ISLAND_RUIN_VALLEY                           30777
#define MAP_SEVEN_ISLAND_TRAINER_TOWER                       30778
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE             30779
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON                      30780
#define MAP_SEVEN_ISLAND_TANOBY_RUINS                        30781
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_1F                     30782
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_2F                     30783
#define MAP_PALLET_TOWN_RIVALS_HOUSE                         30784
#define MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB                   30785
#define MAP_VIRIDIAN_CITY_HOUSE                              30786
#define MAP_VIRIDIAN_CITY_GYM                                30787
#define MAP_VIRIDIAN_CITY_SCHOOL                             30788
#define MAP_VIRIDIAN_CITY_MART                               30789
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F                  30790
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F                  30791
#define MAP_PEWTER_CITY_MUSEUM_1F                            30792
#define MAP_PEWTER_CITY_MUSEUM_2F                            30793
#define MAP_PEWTER_CITY_GYM                                  30794
#define MAP_PEWTER_CITY_MART                                 30795
#define MAP_PEWTER_CITY_HOUSE1                               30796
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F                    30797
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F                    30798
#define MAP_PEWTER_CITY_HOUSE2                               30799
#define MAP_CERULEAN_CITY_HOUSE1                             30800
#define MAP_CERULEAN_CITY_HOUSE2                             30801
#define MAP_CERULEAN_CITY_HOUSE3                             30802
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F                  30803
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F                  30804
#define MAP_CERULEAN_CITY_GYM                                30805
#define MAP_CERULEAN_CITY_BIKE_SHOP                          30806
#define MAP_CERULEAN_CITY_MART                               30807
#define MAP_CERULEAN_CITY_HOUSE4                             30808
#define MAP_CERULEAN_CITY_HOUSE5                             30809
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F                  30810
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F                  30811
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE            30812
#define MAP_LAVENDER_TOWN_HOUSE1                             30813
#define MAP_LAVENDER_TOWN_HOUSE2                             30814
#define MAP_LAVENDER_TOWN_MART                               30815
#define MAP_VERMILION_CITY_HOUSE1                            30816
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F                 30817
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F                 30818
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB                  30819
#define MAP_VERMILION_CITY_HOUSE2                            30820
#define MAP_VERMILION_CITY_MART                              30821
#define MAP_VERMILION_CITY_GYM                               30822
#define MAP_VERMILION_CITY_HOUSE3                            30823
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F                 30976
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F                 30977
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F                 30978
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F                 30979
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F                 30980
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF               30981
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR           30982
#define MAP_CELADON_CITY_CONDOMINIUMS_1F                     30983
#define MAP_CELADON_CITY_CONDOMINIUMS_2F                     30984
#define MAP_CELADON_CITY_CONDOMINIUMS_3F                     30985
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF                   30986
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM              30987
#define MAP_CELADON_CITY_POKEMON_CENTER_1F                   30988
#define MAP_CELADON_CITY_POKEMON_CENTER_2F                   30989
#define MAP_CELADON_CITY_GAME_CORNER                         30990
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM              30991
#define MAP_CELADON_CITY_GYM                                 30992
#define MAP_CELADON_CITY_RESTAURANT                          30993
#define MAP_CELADON_CITY_HOUSE1                              30994
#define MAP_CELADON_CITY_HOTEL                               30995
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE                30996
#define MAP_FUCHSIA_CITY_MART                                30997
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE                  30998
#define MAP_FUCHSIA_CITY_GYM                                 30999
#define MAP_FUCHSIA_CITY_HOUSE1                              31000
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F                   31001
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F                   31002
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE                       31003
#define MAP_FUCHSIA_CITY_HOUSE2                              31004
#define MAP_FUCHSIA_CITY_HOUSE3                              31005
#define MAP_CINNABAR_ISLAND_GYM                              31006
#define MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE             31007
#define MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE               31008
#define MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM        31009
#define MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM      31010
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F                31011
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F                31012
#define MAP_CINNABAR_ISLAND_MART                             31013
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F                 31014
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F                 31015
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F                   31016
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F                   31017
#define MAP_SAFFRON_CITY_DOJO                                31018
#define MAP_SAFFRON_CITY_GYM                                 31019
#define MAP_SAFFRON_CITY_HOUSE                               31020
#define MAP_SAFFRON_CITY_MART                                31021
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F                   31022
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F                   31023
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE                   31024
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB            31025
#define MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE            31026
#define MAP_ROUTE2_EAST_BUILDING                             31028
#define MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE            31029
#define MAP_ROUTE4_POKEMON_CENTER_1F                         31030
#define MAP_ROUTE4_POKEMON_CENTER_2F                         31031
#define MAP_ROUTE5_POKEMON_DAY_CARE                          31032
#define MAP_ROUTE5_SOUTH_ENTRANCE                            31033
#define MAP_ROUTE6_NORTH_ENTRANCE                            31034
#define MAP_ROUTE7_EAST_ENTRANCE                             31035
#define MAP_ROUTE8_WEST_ENTRANCE                             31036
#define MAP_ROUTE10_POKEMON_CENTER_1F                        31037
#define MAP_ROUTE10_POKEMON_CENTER_2F                        31038
#define MAP_ROUTE11_EAST_ENTRANCE_1F                         31039
#define MAP_ROUTE11_EAST_ENTRANCE_2F                         31040
#define MAP_ROUTE12_NORTH_ENTRANCE_1F                        31041
#define MAP_ROUTE12_NORTH_ENTRANCE_2F                        31042
#define MAP_ROUTE12_FISHING_HOUSE                            31043
#define MAP_ROUTE15_WEST_ENTRANCE_1F                         31044
#define MAP_ROUTE15_WEST_ENTRANCE_2F                         31045
#define MAP_ROUTE16_HOUSE                                    31046
#define MAP_ROUTE16_NORTH_ENTRANCE_1F                        31047
#define MAP_ROUTE16_NORTH_ENTRANCE_2F                        31048
#define MAP_ROUTE18_EAST_ENTRANCE_1F                         31049
#define MAP_ROUTE18_EAST_ENTRANCE_2F                         31050
#define MAP_ROUTE22_NORTH_ENTRANCE                           31051
#define MAP_ROUTE25_SEA_COTTAGE                              31052
#define MAP_SEVEN_ISLAND_HOUSE_ROOM1                         31053
#define MAP_SEVEN_ISLAND_HOUSE_ROOM2                         31054
#define MAP_SEVEN_ISLAND_MART                                31055
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F                   31056
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_2F                   31057
#define MAP_SEVEN_ISLAND_HARBOR                              31058
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F                     31059
#define MAP_ONE_ISLAND_POKEMON_CENTER_2F                     31060
#define MAP_ONE_ISLAND_HOUSE1                                31061
#define MAP_ONE_ISLAND_HOUSE2                                31062
#define MAP_ONE_ISLAND_HARBOR                                31063
#define MAP_TWO_ISLAND_JOYFUL_GAME_CORNER                    31064
#define MAP_TWO_ISLAND_HOUSE                                 31065
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F                     31066
#define MAP_TWO_ISLAND_POKEMON_CENTER_2F                     31067
#define MAP_TWO_ISLAND_HARBOR                                31068
#define MAP_THREE_ISLAND_HOUSE1                              31069
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F                   31070
#define MAP_THREE_ISLAND_POKEMON_CENTER_2F                   31071
#define MAP_THREE_ISLAND_MART                                31072
#define MAP_THREE_ISLAND_HOUSE2                              31073
#define MAP_THREE_ISLAND_HOUSE3                              31074
#define MAP_THREE_ISLAND_HOUSE4                              31075
#define MAP_THREE_ISLAND_HOUSE5                              31076
#define MAP_FOUR_ISLAND_POKEMON_DAY_CARE                     31077
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F                    31078
#define MAP_FOUR_ISLAND_POKEMON_CENTER_2F                    31079
#define MAP_FOUR_ISLAND_HOUSE1                               31080
#define MAP_FOUR_ISLAND_LORELEIS_HOUSE                       31081
#define MAP_FOUR_ISLAND_HARBOR                               31082
#define MAP_FOUR_ISLAND_HOUSE2                               31083
#define MAP_FOUR_ISLAND_MART                                 31084
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F                    31085
#define MAP_FIVE_ISLAND_POKEMON_CENTER_2F                    31086
#define MAP_FIVE_ISLAND_HARBOR                               31087
#define MAP_FIVE_ISLAND_HOUSE1                               31088
#define MAP_FIVE_ISLAND_HOUSE2                               31089
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F                     31090
#define MAP_SIX_ISLAND_POKEMON_CENTER_2F                     31091
#define MAP_SIX_ISLAND_HARBOR                                31092
#define MAP_SIX_ISLAND_HOUSE                                 31093
#define MAP_SIX_ISLAND_MART                                  31094
#define MAP_THREE_ISLAND_HARBOR                              31095
#define MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE                31096
#define MAP_TWO_ISLAND_CAPE_BRINK_HOUSE                      31097
#define MAP_SIX_ISLAND_WATER_PATH_HOUSE1                     31098
#define MAP_SIX_ISLAND_WATER_PATH_HOUSE2                     31099
#define MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE                31100
#define MAP_VIRIDIAN_FOREST                                  31232
#define MAP_MT_MOON_1F                                       31233
#define MAP_MT_MOON_B1F                                      31234
#define MAP_MT_MOON_B2F                                      31235
#define MAP_SSANNE_EXTERIOR                                  31236
#define MAP_SSANNE_1F_CORRIDOR                               31237
#define MAP_SSANNE_2F_CORRIDOR                               31238
#define MAP_SSANNE_3F_CORRIDOR                               31239
#define MAP_SSANNE_B1F_CORRIDOR                              31240
#define MAP_SSANNE_DECK                                      31241
#define MAP_SSANNE_KITCHEN                                   31242
#define MAP_SSANNE_CAPTAINS_OFFICE                           31243
#define MAP_SSANNE_1F_ROOM1                                  31244
#define MAP_SSANNE_1F_ROOM2                                  31245
#define MAP_SSANNE_1F_ROOM3                                  31246
#define MAP_SSANNE_1F_ROOM4                                  31247
#define MAP_SSANNE_1F_ROOM5                                  31248
#define MAP_SSANNE_1F_ROOM7                                  31249
#define MAP_SSANNE_2F_ROOM1                                  31250
#define MAP_SSANNE_2F_ROOM2                                  31251
#define MAP_SSANNE_2F_ROOM3                                  31252
#define MAP_SSANNE_2F_ROOM4                                  31253
#define MAP_SSANNE_2F_ROOM5                                  31254
#define MAP_SSANNE_2F_ROOM6                                  31255
#define MAP_SSANNE_B1F_ROOM1                                 31256
#define MAP_SSANNE_B1F_ROOM2                                 31257
#define MAP_SSANNE_B1F_ROOM3                                 31258
#define MAP_SSANNE_B1F_ROOM4                                 31259
#define MAP_SSANNE_B1F_ROOM5                                 31260
#define MAP_SSANNE_1F_ROOM6                                  31261
#define MAP_UNDERGROUND_PATH_NORTH_ENTRANCE                  31262
#define MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL              31263
#define MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE                  31264
#define MAP_UNDERGROUND_PATH_WEST_ENTRANCE                   31265
#define MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL                31266
#define MAP_UNDERGROUND_PATH_EAST_ENTRANCE                   31267
#define MAP_DIGLETTS_CAVE_NORTH_ENTRANCE                     31268
#define MAP_DIGLETTS_CAVE_B1F                                31269
#define MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE                     31270
#define MAP_VICTORY_ROAD_1F_FRLG                             31271
#define MAP_VICTORY_ROAD_2F                                  31272
#define MAP_VICTORY_ROAD_3F                                  31273
#define MAP_ROCKET_HIDEOUT_B1F                               31274
#define MAP_ROCKET_HIDEOUT_B2F                               31275
#define MAP_ROCKET_HIDEOUT_B3F                               31276
#define MAP_ROCKET_HIDEOUT_B4F                               31277
#define MAP_ROCKET_HIDEOUT_ELEVATOR                          31278
#define MAP_SILPH_CO_1F                                      31279
#define MAP_SILPH_CO_2F                                      31280
#define MAP_SILPH_CO_3F                                      31281
#define MAP_SILPH_CO_4F                                      31282
#define MAP_SILPH_CO_5F                                      31283
#define MAP_SILPH_CO_6F                                      31284
#define MAP_SILPH_CO_7F                                      31285
#define MAP_SILPH_CO_8F                                      31286
#define MAP_SILPH_CO_9F                                      31287
#define MAP_SILPH_CO_10F                                     31288
#define MAP_SILPH_CO_11F                                     31289
#define MAP_SILPH_CO_ELEVATOR                                31290
#define MAP_POKEMON_MANSION_1F                               31291
#define MAP_POKEMON_MANSION_2F                               31292
#define MAP_POKEMON_MANSION_3F                               31293
#define MAP_POKEMON_MANSION_B1F                              31294

// Required Layouts
#define LAYOUT_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_UNUSED         0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            0xFFFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              0xFFFF
#define LAYOUT_BATTLE_TENT_CORRIDOR                            0xFFFF
#define LAYOUT_BATTLE_TENT_BATTLE_ROOM                         0xFFFF
#define LAYOUT_ALTERING_CAVE                                   0xFFFF
#define LAYOUT_TRAINER_HILL_1F                                 0xFFFF
#define LAYOUT_TRAINER_HILL_2F                                 0xFFFF
#define LAYOUT_TRAINER_HILL_3F                                 0xFFFF
#define LAYOUT_TRAINER_HILL_4F                                 0xFFFF
#define LAYOUT_TRAINER_HILL_ROOF                               0xFFFF
#define LAYOUT_TRAINER_HILL_ENTRANCE                           0xFFFF
#define LAYOUT_TRAINER_TOWER_1F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_LOBBY                             0xFFFF
#define LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_2F_FRLG               0xFFFF
#define LAYOUT_TRAINER_TOWER_LOBBY                             0xFFFF
#define LAYOUT_TRAINER_TOWER_1F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_2F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_3F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_4F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_5F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_6F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_7F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_8F                                0xFFFF
#define LAYOUT_TRAINER_TOWER_1F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_2F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_3F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_4F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_5F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_6F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_7F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_8F_DOUBLES                        0xFFFF
#define LAYOUT_TRAINER_TOWER_1F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_2F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_3F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_4F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_5F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_6F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_7F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_8F_KNOCKOUT                       0xFFFF
#define LAYOUT_TRAINER_TOWER_ROOF                              0xFFFF
#define LAYOUT_SS_TIDAL_CORRIDOR                               0xFFFD
#define LAYOUT_SS_TIDAL_LOWER_DECK                             0xFFFE
#define LAYOUT_SS_TIDAL_ROOMS                                  0xFFFF

// Required LocalIDs
#define LOCALID_APPRENTICE 0
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 0
#define LOCALID_BLEND_MASTER 0
#define LOCALID_CAPE_BRINK_TUTOR 0
#define LOCALID_CONTEST_AUDIENCE_1 0
#define LOCALID_CONTEST_AUDIENCE_2 0
#define LOCALID_CONTEST_AUDIENCE_3 0
#define LOCALID_CONTEST_AUDIENCE_4 0
#define LOCALID_CONTEST_AUDIENCE_5 0
#define LOCALID_CONTEST_AUDIENCE_6 0
#define LOCALID_CONTEST_AUDIENCE_7 0
#define LOCALID_CONTEST_ARTIST 0
#define LOCALID_CONTEST_JUDGE 0
#define LOCALID_CONTEST_LOBBY_BLENDER_2_LEADER 0
#define LOCALID_CONTEST_LOBBY_BLENDER_2_PARTICIPANT 0
#define LOCALID_CONTEST_LOBBY_BLENDER_3_LEADER 0
#define LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_1 0
#define LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_2 0
#define LOCALID_CONTEST_MC 0
#define LOCALID_CONTEST_POKEBALL 0
#define LOCALID_CONTESTANT_1 0
#define LOCALID_CONTESTANT_2 0
#define LOCALID_CONTESTANT_3 0
#define LOCALID_CONTESTANT_4 0
#define LOCALID_DAYCARE_LADY 0
#define LOCALID_FALLARBOR_MART_CLERK 0
#define LOCALID_FARAWAY_ISLAND_MEW 0
#define LOCALID_FORTREE_MART_CLERK 0
#define LOCALID_FRONTIER_MART_CLERK 0
#define LOCALID_LAVARIDGE_MART_CLERK 0
#define LOCALID_LILYCOVE_LADY 0
#define LOCALID_LILYCOVE_LADYS_MON 0
#define LOCALID_MAUVILLE_MART_CLERK 0
#define LOCALID_MOSSDEEP_MART_CLERK 0
#define LOCALID_OLDALE_MART_CLERK 0
#define LOCALID_PETALBURG_MART_CLERK 0
#define LOCALID_PIKE_ROOM_NPC_1 0
#define LOCALID_PIKE_ROOM_NPC_2 0
#define LOCALID_PLAYERS_HOUSE_1F_DAD 0
#define LOCALID_PLAYERS_HOUSE_1F_MOM 0
#define LOCALID_PLAYERS_HOUSE_2F_MOM 0
#define LOCALID_ROUTE111_GABBY_1 0
#define LOCALID_ROUTE111_GABBY_2 0
#define LOCALID_ROUTE111_GABBY_3 0
#define LOCALID_ROUTE111_TY_1 0
#define LOCALID_ROUTE111_TY_2 0
#define LOCALID_ROUTE111_TY_3 0
#define LOCALID_ROUTE111_PLAYER_FALLING 0
#define LOCALID_ROUTE118_GABBY_1 0
#define LOCALID_ROUTE118_GABBY_2 0
#define LOCALID_ROUTE118_GABBY_3 0
#define LOCALID_ROUTE118_TY_1 0
#define LOCALID_ROUTE118_TY_2 0
#define LOCALID_ROUTE118_TY_3 0
#define LOCALID_ROUTE120_GABBY_1 0
#define LOCALID_ROUTE120_GABBY_2 0
#define LOCALID_ROUTE120_TY_1 0
#define LOCALID_ROUTE120_TY_2 0
#define LOCALID_RUSTBORO_MART_CLERK 0
#define LOCALID_RUSTURF_TUNNEL_WANDA 0
#define LOCALID_RUSTURF_TUNNEL_WANDAS_BF 0
#define LOCALID_SLATEPORT_ENERGY_GURU 0
#define LOCALID_SLATEPORT_MART_CLERK 0
#define LOCALID_SOOTOPOLIS_MART_CLERK 0
#define LOCALID_TOWER_LOBBY_REPORTER 0
#define LOCALID_TOWER_TRAINER_KNOCKOUT 0
#define LOCALID_TOWER_TRAINER_DOUBLES1 0
#define LOCALID_TOWER_TRAINER_DOUBLES2 0
#define LOCALID_TOWER_TRAINER_SINGLES 0
#define LOCALID_TRUCK_BOX_TOP 0
#define LOCALID_TRUCK_BOX_BOTTOM_L 0
#define LOCALID_TRUCK_BOX_BOTTOM_R 0
#define LOCALID_UNION_ROOM_PLAYER_1 0
#define LOCALID_UNION_ROOM_PLAYER_2 0
#define LOCALID_UNION_ROOM_PLAYER_3 0
#define LOCALID_UNION_ROOM_PLAYER_4 0
#define LOCALID_UNION_ROOM_PLAYER_5 0
#define LOCALID_UNION_ROOM_PLAYER_6 0
#define LOCALID_UNION_ROOM_PLAYER_7 0
#define LOCALID_UNION_ROOM_PLAYER_8 0
#define LOCALID_VERDANTURF_MART_CLERK 0
#define LOCALID_VERMILION_FERRY_SAILOR 0

// Required Heal Locations
#define HEAL_LOCATION_LAVARIDGE_TOWN 0xFF
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 0xFF
#define HEAL_LOCATION_CELADON_CITY 0xFF
#define HEAL_LOCATION_CERULEAN_CITY 0xFF
#define HEAL_LOCATION_CINNABAR_ISLAND 0xFF
#define HEAL_LOCATION_DEWFORD_TOWN 0xFF
#define HEAL_LOCATION_EVER_GRANDE_CITY 0xFF
#define HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE 0xFF
#define HEAL_LOCATION_FALLARBOR_TOWN 0xFF
#define HEAL_LOCATION_FORTREE_CITY 0xFF
#define HEAL_LOCATION_FOUR_ISLAND 0xFF
#define HEAL_LOCATION_FIVE_ISLAND 0xFF
#define HEAL_LOCATION_FUCHSIA_CITY 0xFF
#define HEAL_LOCATION_INDIGO_PLATEAU 0xFF
#define HEAL_LOCATION_LAVARIDGE_TOWN 0xFF
#define HEAL_LOCATION_LAVENDER_TOWN 0xFF
#define HEAL_LOCATION_LILYCOVE_CITY 0xFF
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE 0xFF
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F 0xFF
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE 0xFF
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F 0xFF
#define HEAL_LOCATION_MAUVILLE_CITY 0xFF
#define HEAL_LOCATION_MOSSDEEP_CITY 0xFF
#define HEAL_LOCATION_OLDALE_TOWN 0xFF
#define HEAL_LOCATION_ONE_ISLAND 0xFF
#define HEAL_LOCATION_PACIFIDLOG_TOWN 0xFF
#define HEAL_LOCATION_PALLET_TOWN 0xFF
#define HEAL_LOCATION_PETALBURG_CITY 0xFF
#define HEAL_LOCATION_PEWTER_CITY 0xFF
#define HEAL_LOCATION_ROUTE4 0xFF
#define HEAL_LOCATION_ROUTE10 0xFF
#define HEAL_LOCATION_RUSTBORO_CITY 0xFF
#define HEAL_LOCATION_SAFFRON_CITY 0xFF
#define HEAL_LOCATION_SEVEN_ISLAND 0xFF
#define HEAL_LOCATION_SIX_ISLAND 0xFF
#define HEAL_LOCATION_SLATEPORT_CITY 0xFF
#define HEAL_LOCATION_SOOTOPOLIS_CITY 0xFF
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 0xFF
#define HEAL_LOCATION_THREE_ISLAND 0xFF
#define HEAL_LOCATION_TWO_ISLAND 0xFF
#define HEAL_LOCATION_VERDANTURF_TOWN 0xFF
#define HEAL_LOCATION_VERMILION_CITY 0xFF
#define HEAL_LOCATION_VIRIDIAN_CITY 0xFF

#endif // GUARD_CONSTANTS_DUMMY_MAP_DEFINES_H