#ifndef GUARD_METATILE_LABELS_H
#define GUARD_METATILE_LABELS_H

// gTileset_Abalove
#define METATILE_Abalove_LedgeTop                0x221
#define METATILE_Abalove_LongGrass_LedgeTop      0x28D
#define METATILE_Abalove_LongGrass_SmallTreeTop  0x295

// gTileset_Armiter
#define METATILE_Armiter_Grass                      0x200
#define METATILE_Armiter_Leaves                     0x249
#define METATILE_Armiter_Leaves_TreeLeft_1          0x208
#define METATILE_Armiter_Leaves_TreeLeft_2          0x20A
#define METATILE_Armiter_Leaves_TreeLeft_3          0x20C
#define METATILE_Armiter_Leaves_TreeRight_1         0x209
#define METATILE_Armiter_Leaves_TreeRight_2         0x20B
#define METATILE_Armiter_Leaves_TreeRight_3         0x20D
#define METATILE_Armiter_TallGrass_Green            0x207
#define METATILE_Armiter_TallGrass_Red              0x23F
#define METATILE_Armiter_TallGrass_Red_TreeLeft_1   0x238
#define METATILE_Armiter_TallGrass_Red_TreeLeft_2   0x23A
#define METATILE_Armiter_TallGrass_Red_TreeLeft_3   0x23C
#define METATILE_Armiter_TallGrass_Red_TreeRight_1  0x239
#define METATILE_Armiter_TallGrass_Red_TreeRight_2  0x23B
#define METATILE_Armiter_TallGrass_Red_TreeRight_3  0x23D

// gTileset_Building
#define METATILE_Building_TV_Off  0x003
#define METATILE_Building_TV_On   0x004

// gTileset_MountBriar
#define METATILE_MountBriar_Snow                       0x200
#define METATILE_MountBriar_Snow_TreeLeft              0x202
#define METATILE_MountBriar_Snow_TreeRight             0x203
#define METATILE_MountBriar_TallGrass_Clear            0x209
#define METATILE_MountBriar_TallGrass_Clear_TreeLeft   0x20E
#define METATILE_MountBriar_TallGrass_Clear_TreeRight  0x20F
#define METATILE_MountBriar_TallGrass_Snowy            0x201
#define METATILE_MountBriar_TallGrass_Snowy_TreeLeft   0x206
#define METATILE_MountBriar_TallGrass_Snowy_TreeRight  0x207

// gTileset_Nautirust
#define METATILE_Nautirust_BigTree_Left               0x208
#define METATILE_Nautirust_BigTree_Mid                0x201
#define METATILE_Nautirust_BigTree_Right              0x20A
#define METATILE_Nautirust_LongGrassBottom_TreeLeft   0x217
#define METATILE_Nautirust_LongGrassBottom_TreeMid    0x216
#define METATILE_Nautirust_LongGrassBottom_TreeRight  0x215
#define METATILE_Nautirust_TallGrass_Flower1          0x329
#define METATILE_Nautirust_TallGrass_Flower2          0x32A
#define METATILE_Nautirust_TallGrass_Flower3          0x32B
#define METATILE_Nautirust_TallGrass_Flower4          0x32C
#define METATILE_Nautirust_TallGrass_TreeMid          0x221

// gTileset_Overworld
#define METATILE_Overworld_CaveEntranceBottom       0x04F
#define METATILE_Overworld_CaveEntranceTop          0x047
#define METATILE_Overworld_CliffBottom_BrownShadow  0x034
#define METATILE_Overworld_CliffBottom_GreyShadow   0x031
#define METATILE_Overworld_Door_Glass               0x192
#define METATILE_Overworld_Door_Wood                0x1B6
#define METATILE_Overworld_Grass                    0x001
#define METATILE_Overworld_Grass_LedgeTop           0x029
#define METATILE_Overworld_Grass_SmallTreeTop       0x006
#define METATILE_Overworld_Grass_TreeLeft           0x008
#define METATILE_Overworld_Grass_TreeRight          0x009
#define METATILE_Overworld_LongGrassBottom          0x01F
#define METATILE_Overworld_LongGrassMid             0x017
#define METATILE_Overworld_LongGrassTop             0x00F
#define METATILE_Overworld_LongGrassTop_LedgeTop    0x16B
#define METATILE_Overworld_TallGrass                0x007
#define METATILE_Overworld_TallGrass_SmallTreeTop   0x069
#define METATILE_Overworld_TallGrass_TreeLeft       0x00C
#define METATILE_Overworld_TallGrass_TreeRight      0x00D

// gTileset_PlayerHouse
#define METATILE_PlayerHouse_PC_Off  0x23B
#define METATILE_PlayerHouse_PC_On   0x23C
#define METATILE_PlayerHouse_TV_Off  0x28F

// gTileset_PokemonCenter
#define METATILE_PokemonCenter_PC_Off  0x246
#define METATILE_PokemonCenter_PC_On   0x247

// gTileset_SecretBase
#define METATILE_SecretBase_AttractMat_BottomLeft       0x313
#define METATILE_SecretBase_AttractMat_BottomMid        0x314
#define METATILE_SecretBase_AttractMat_BottomRight      0x315
#define METATILE_SecretBase_AttractMat_Center           0x30C
#define METATILE_SecretBase_AttractMat_MidLeft          0x30B
#define METATILE_SecretBase_AttractMat_MidRight         0x30D
#define METATILE_SecretBase_AttractMat_TopLeft          0x303
#define METATILE_SecretBase_AttractMat_TopMid           0x304
#define METATILE_SecretBase_AttractMat_TopRight         0x305
#define METATILE_SecretBase_BallPoster                  0x330
#define METATILE_SecretBase_BigPlant_BaseLeft1          0x2EC
#define METATILE_SecretBase_BigPlant_BaseLeft2          0x2EE
#define METATILE_SecretBase_BigPlant_BaseRight1         0x2ED
#define METATILE_SecretBase_BigPlant_BaseRight2         0x2EF
#define METATILE_SecretBase_BigPlant_TopLeft            0x2E4
#define METATILE_SecretBase_BigPlant_TopRight           0x2E6
#define METATILE_SecretBase_BlueBalloon                 0x33C
#define METATILE_SecretBase_BlueBrick_Bottom            0x22F
#define METATILE_SecretBase_BlueBrick_Top               0x227
#define METATILE_SecretBase_BluePoster                  0x333
#define METATILE_SecretBase_BlueTent_BottomLeft         0x258
#define METATILE_SecretBase_BlueTent_BottomRight        0x269
#define METATILE_SecretBase_BlueTent_Door               0x259
#define METATILE_SecretBase_BlueTent_DoorTop            0x251
#define METATILE_SecretBase_BlueTent_MidLeft            0x250
#define METATILE_SecretBase_BlueTent_MidRight           0x270
#define METATILE_SecretBase_BlueTent_TopLeft            0x248
#define METATILE_SecretBase_BlueTent_TopMid             0x249
#define METATILE_SecretBase_BlueTent_TopRight           0x268
#define METATILE_SecretBase_BreakableDoor_BottomClosed  0x23F
#define METATILE_SecretBase_BreakableDoor_BottomOpen    0x276
#define METATILE_SecretBase_BreakableDoor_TopClosed     0x237
#define METATILE_SecretBase_BreakableDoor_TopOpen       0x26E
#define METATILE_SecretBase_BrickChair                  0x2C8
#define METATILE_SecretBase_BrickDesk_BottomLeft        0x2B0
#define METATILE_SecretBase_BrickDesk_BottomMid         0x2B1
#define METATILE_SecretBase_BrickDesk_BottomRight       0x2B2
#define METATILE_SecretBase_BrickDesk_Center            0x2A9
#define METATILE_SecretBase_BrickDesk_MidLeft           0x2A8
#define METATILE_SecretBase_BrickDesk_MidRight          0x2AA
#define METATILE_SecretBase_BrickDesk_TopLeft           0x2A0
#define METATILE_SecretBase_BrickDesk_TopMid            0x2A1
#define METATILE_SecretBase_BrickDesk_TopRight          0x2A2
#define METATILE_SecretBase_CampChair                   0x2C9
#define METATILE_SecretBase_CampDesk_BottomLeft         0x2B4
#define METATILE_SecretBase_CampDesk_BottomMid          0x2B5
#define METATILE_SecretBase_CampDesk_BottomRight        0x2B6
#define METATILE_SecretBase_CampDesk_Center             0x2AD
#define METATILE_SecretBase_CampDesk_MidLeft            0x2AC
#define METATILE_SecretBase_CampDesk_MidRight           0x2AE
#define METATILE_SecretBase_CampDesk_TopLeft            0x2A4
#define METATILE_SecretBase_CampDesk_TopMid             0x2A5
#define METATILE_SecretBase_CampDesk_TopRight           0x2A6
#define METATILE_SecretBase_ColorfulPlant_BaseLeft1     0x2E8
#define METATILE_SecretBase_ColorfulPlant_BaseLeft2     0x2EA
#define METATILE_SecretBase_ColorfulPlant_BaseRight1    0x2E9
#define METATILE_SecretBase_ColorfulPlant_BaseRight2    0x2EB
#define METATILE_SecretBase_ColorfulPlant_TopLeft       0x2E0
#define METATILE_SecretBase_ColorfulPlant_TopLeftWall   0x2E1
#define METATILE_SecretBase_ColorfulPlant_TopRight      0x2E2
#define METATILE_SecretBase_ColorfulPlant_TopRightWall  0x2E3
#define METATILE_SecretBase_ComfortChair                0x2C1
#define METATILE_SecretBase_ComfortDesk_BottomLeft      0x29E
#define METATILE_SecretBase_ComfortDesk_BottomMid       0x29F
#define METATILE_SecretBase_ComfortDesk_BottomRight     0x2AB
#define METATILE_SecretBase_ComfortDesk_TopLeft         0x296
#define METATILE_SecretBase_ComfortDesk_TopMid          0x297
#define METATILE_SecretBase_ComfortDesk_TopRight        0x2A3
#define METATILE_SecretBase_CutePoster                  0x334
#define METATILE_SecretBase_CuteTV                      0x2F6
#define METATILE_SecretBase_Fence_Horizontal            0x22C
#define METATILE_SecretBase_Fence_Vertical              0x233
#define METATILE_SecretBase_FireBlastMat_BottomLeft     0x265
#define METATILE_SecretBase_FireBlastMat_BottomMid      0x266
#define METATILE_SecretBase_FireBlastMat_BottomRight    0x267
#define METATILE_SecretBase_FireBlastMat_Center         0x25E
#define METATILE_SecretBase_FireBlastMat_MidLeft        0x25D
#define METATILE_SecretBase_FireBlastMat_MidRight       0x25F
#define METATILE_SecretBase_FireBlastMat_TopLeft        0x25A
#define METATILE_SecretBase_FireBlastMat_TopMid         0x25B
#define METATILE_SecretBase_FireBlastMat_TopRight       0x25C
#define METATILE_SecretBase_FissureMat_BottomLeft       0x316
#define METATILE_SecretBase_FissureMat_BottomMid        0x317
#define METATILE_SecretBase_FissureMat_BottomRight      0x328
#define METATILE_SecretBase_FissureMat_Center           0x30F
#define METATILE_SecretBase_FissureMat_MidLeft          0x30E
#define METATILE_SecretBase_FissureMat_MidRight         0x320
#define METATILE_SecretBase_FissureMat_TopLeft          0x306
#define METATILE_SecretBase_FissureMat_TopMid           0x307
#define METATILE_SecretBase_FissureMat_TopRight         0x318
#define METATILE_SecretBase_GlassOrnament_Base1         0x28A
#define METATILE_SecretBase_GlassOrnament_Base2         0x28B
#define METATILE_SecretBase_GlassOrnament_Top           0x282
#define METATILE_SecretBase_GlassOrnament_TopWall       0x283
#define METATILE_SecretBase_GlitterMat                  0x260
#define METATILE_SecretBase_GoldShield_Base1            0x336
#define METATILE_SecretBase_GoldShield_Base2            0x337
#define METATILE_SecretBase_GoldShield_Top              0x32E
#define METATILE_SecretBase_GoldShield_TopWall          0x32F
#define METATILE_SecretBase_GorgeousPlant_BaseLeft1     0x2F8
#define METATILE_SecretBase_GorgeousPlant_BaseLeft2     0x2FA
#define METATILE_SecretBase_GorgeousPlant_BaseRight1    0x2F9
#define METATILE_SecretBase_GorgeousPlant_BaseRight2    0x2FB
#define METATILE_SecretBase_GorgeousPlant_TopLeft       0x2F0
#define METATILE_SecretBase_GorgeousPlant_TopLeftWall   0x2F1
#define METATILE_SecretBase_GorgeousPlant_TopRight      0x2F2
#define METATILE_SecretBase_GorgeousPlant_TopRightWall  0x2F3
#define METATILE_SecretBase_GreenPoster                 0x331
#define METATILE_SecretBase_Ground                      0x20A
#define METATILE_SecretBase_HardChair                   0x2CA
#define METATILE_SecretBase_HardDesk_BottomLeft         0x2B7
#define METATILE_SecretBase_HardDesk_BottomMid          0x2CB
#define METATILE_SecretBase_HardDesk_BottomRight        0x2CC
#define METATILE_SecretBase_HardDesk_Center             0x2C3
#define METATILE_SecretBase_HardDesk_MidLeft            0x2AF
#define METATILE_SecretBase_HardDesk_MidRight           0x2C4
#define METATILE_SecretBase_HardDesk_TopLeft            0x2A7
#define METATILE_SecretBase_HardDesk_TopMid             0x2BB
#define METATILE_SecretBase_HardDesk_TopRight           0x2BC
#define METATILE_SecretBase_HeavyChair                  0x2BA
#define METATILE_SecretBase_HeavyDesk_BottomLeft        0x298
#define METATILE_SecretBase_HeavyDesk_BottomMid         0x299
#define METATILE_SecretBase_HeavyDesk_BottomRight       0x29A
#define METATILE_SecretBase_HeavyDesk_TopLeft           0x290
#define METATILE_SecretBase_HeavyDesk_TopMid            0x291
#define METATILE_SecretBase_HeavyDesk_TopRight          0x292
#define METATILE_SecretBase_JumpMat                     0x261
#define METATILE_SecretBase_KissPoster_Left             0x32C
#define METATILE_SecretBase_KissPoster_Right            0x32D
#define METATILE_SecretBase_LongPoster_Left             0x31E
#define METATILE_SecretBase_LongPoster_Right            0x31F
#define METATILE_SecretBase_MudBall                     0x228
#define METATILE_SecretBase_NoteMat_A                   0x27D
#define METATILE_SecretBase_NoteMat_B                   0x27E
#define METATILE_SecretBase_NoteMat_C_High              0x2B3
#define METATILE_SecretBase_NoteMat_C_Low               0x278
#define METATILE_SecretBase_NoteMat_D                   0x279
#define METATILE_SecretBase_NoteMat_E                   0x27A
#define METATILE_SecretBase_NoteMat_F                   0x27B
#define METATILE_SecretBase_NoteMat_G                   0x27C
#define METATILE_SecretBase_PC                          0x220
#define METATILE_SecretBase_PC_On                       0x224
#define METATILE_SecretBase_PikaPoster_Left             0x31C
#define METATILE_SecretBase_PikaPoster_Right            0x31D
#define METATILE_SecretBase_PokemonChair                0x2B9
#define METATILE_SecretBase_PokemonDesk                 0x28F
#define METATILE_SecretBase_PowderSnowMat_BottomLeft    0x310
#define METATILE_SecretBase_PowderSnowMat_BottomMid     0x311
#define METATILE_SecretBase_PowderSnowMat_BottomRight   0x312
#define METATILE_SecretBase_PowderSnowMat_Center        0x309
#define METATILE_SecretBase_PowderSnowMat_MidLeft       0x308
#define METATILE_SecretBase_PowderSnowMat_MidRight      0x30A
#define METATILE_SecretBase_PowderSnowMat_TopLeft       0x300
#define METATILE_SecretBase_PowderSnowMat_TopMid        0x301
#define METATILE_SecretBase_PowderSnowMat_TopRight      0x302
#define METATILE_SecretBase_PrettyChair                 0x2C0
#define METATILE_SecretBase_PrettyDesk_BottomLeft       0x2CD
#define METATILE_SecretBase_PrettyDesk_BottomMid        0x2CE
#define METATILE_SecretBase_PrettyDesk_BottomRight      0x2CF
#define METATILE_SecretBase_PrettyDesk_Center           0x2C6
#define METATILE_SecretBase_PrettyDesk_MidLeft          0x2C5
#define METATILE_SecretBase_PrettyDesk_MidRight         0x2C7
#define METATILE_SecretBase_PrettyDesk_TopLeft          0x2BD
#define METATILE_SecretBase_PrettyDesk_TopMid           0x2BE
#define METATILE_SecretBase_PrettyDesk_TopRight         0x2BF
#define METATILE_SecretBase_PrettyFlowers_Base1         0x2DC
#define METATILE_SecretBase_PrettyFlowers_Base2         0x2DD
#define METATILE_SecretBase_PrettyFlowers_Top           0x2D4
#define METATILE_SecretBase_PrettyFlowers_TopWall       0x2D5
#define METATILE_SecretBase_RaggedChair                 0x2C2
#define METATILE_SecretBase_RaggedDesk_BottomLeft       0x29B
#define METATILE_SecretBase_RaggedDesk_BottomMid        0x29C
#define METATILE_SecretBase_RaggedDesk_BottomRight      0x29D
#define METATILE_SecretBase_RaggedDesk_TopLeft          0x293
#define METATILE_SecretBase_RaggedDesk_TopMid           0x294
#define METATILE_SecretBase_RaggedDesk_TopRight         0x295
#define METATILE_SecretBase_RedBalloon                  0x338
#define METATILE_SecretBase_RedBrick_Bottom             0x22D
#define METATILE_SecretBase_RedBrick_Top                0x225
#define METATILE_SecretBase_RedPlant_Base1              0x2D8
#define METATILE_SecretBase_RedPlant_Base2              0x2D9
#define METATILE_SecretBase_RedPlant_Top                0x2D0
#define METATILE_SecretBase_RedPlant_TopWall            0x2D1
#define METATILE_SecretBase_RedPoster                   0x332
#define METATILE_SecretBase_RedTent_BottomLeft          0x240
#define METATILE_SecretBase_RedTent_BottomRight         0x23B
#define METATILE_SecretBase_RedTent_Door                0x241
#define METATILE_SecretBase_RedTent_DoorTop             0x239
#define METATILE_SecretBase_RedTent_MidLeft             0x238
#define METATILE_SecretBase_RedTent_MidRight            0x23A
#define METATILE_SecretBase_RedTent_TopLeft             0x230
#define METATILE_SecretBase_RedTent_TopMid              0x231
#define METATILE_SecretBase_RedTent_TopRight            0x232
#define METATILE_SecretBase_RegisterPC                  0x221
#define METATILE_SecretBase_RoundTV                     0x2F5
#define METATILE_SecretBase_SandOrnament_Base1          0x28D
#define METATILE_SecretBase_SandOrnament_Base2          0x28E
#define METATILE_SecretBase_SandOrnament_BrokenBase     0x28C
#define METATILE_SecretBase_SandOrnament_BrokenTop      0x284
#define METATILE_SecretBase_SandOrnament_Top            0x285
#define METATILE_SecretBase_SandOrnament_TopWall        0x286
#define METATILE_SecretBase_SeaPoster_Left              0x324
#define METATILE_SecretBase_SeaPoster_Right             0x325
#define METATILE_SecretBase_SilverShield_Base1          0x2DE
#define METATILE_SecretBase_SilverShield_Base2          0x2DF
#define METATILE_SecretBase_SilverShield_Top            0x2D6
#define METATILE_SecretBase_SilverShield_TopWall        0x2D7
#define METATILE_SecretBase_SkyPoster_Left              0x326
#define METATILE_SecretBase_SkyPoster_Right             0x327
#define METATILE_SecretBase_Slide_MatLeft               0x26F
#define METATILE_SecretBase_Slide_MatRight              0x277
#define METATILE_SecretBase_Slide_SlideBottom           0x264
#define METATILE_SecretBase_Slide_SlideTop              0x23E
#define METATILE_SecretBase_Slide_StairLanding          0x23D
#define METATILE_SecretBase_Slide_Stairs                0x263
#define METATILE_SecretBase_Slide_TopLeft               0x235
#define METATILE_SecretBase_Slide_TopRight              0x236
#define METATILE_SecretBase_SmallChair                  0x2B8
#define METATILE_SecretBase_SmallDesk                   0x287
#define METATILE_SecretBase_SolidBoard_Bottom           0x23C
#define METATILE_SecretBase_SolidBoard_Top              0x234
#define METATILE_SecretBase_SpikesMat_BottomLeft        0x329
#define METATILE_SecretBase_SpikesMat_BottomMid         0x32A
#define METATILE_SecretBase_SpikesMat_BottomRight       0x32B
#define METATILE_SecretBase_SpikesMat_Center            0x322
#define METATILE_SecretBase_SpikesMat_MidLeft           0x321
#define METATILE_SecretBase_SpikesMat_MidRight          0x323
#define METATILE_SecretBase_SpikesMat_TopLeft           0x319
#define METATILE_SecretBase_SpikesMat_TopMid            0x31A
#define METATILE_SecretBase_SpikesMat_TopRight          0x31B
#define METATILE_SecretBase_SpinMat                     0x262
#define METATILE_SecretBase_Stand_BaseLeft              0x273
#define METATILE_SecretBase_Stand_BaseRight             0x274
#define METATILE_SecretBase_Stand_CornerLeft            0x26A
#define METATILE_SecretBase_Stand_CornerRight           0x26D
#define METATILE_SecretBase_Stand_MidLeft               0x26B
#define METATILE_SecretBase_Stand_MidRight              0x26C
#define METATILE_SecretBase_Stand_StairsLeft            0x272
#define METATILE_SecretBase_Stand_StairsRight           0x275
#define METATILE_SecretBase_SurfMat_BottomLeft          0x252
#define METATILE_SecretBase_SurfMat_BottomMid           0x253
#define METATILE_SecretBase_SurfMat_BottomRight         0x254
#define METATILE_SecretBase_SurfMat_Center              0x24B
#define METATILE_SecretBase_SurfMat_MidLeft             0x24A
#define METATILE_SecretBase_SurfMat_MidRight            0x24C
#define METATILE_SecretBase_SurfMat_TopLeft             0x242
#define METATILE_SecretBase_SurfMat_TopMid              0x243
#define METATILE_SecretBase_SurfMat_TopRight            0x244
#define METATILE_SecretBase_TV                          0x2F4
#define METATILE_SecretBase_ThunderMat_BottomLeft       0x255
#define METATILE_SecretBase_ThunderMat_BottomMid        0x256
#define METATILE_SecretBase_ThunderMat_BottomRight      0x257
#define METATILE_SecretBase_ThunderMat_Center           0x24E
#define METATILE_SecretBase_ThunderMat_MidLeft          0x24D
#define METATILE_SecretBase_ThunderMat_MidRight         0x24F
#define METATILE_SecretBase_ThunderMat_TopLeft          0x245
#define METATILE_SecretBase_ThunderMat_TopMid           0x246
#define METATILE_SecretBase_ThunderMat_TopRight         0x247
#define METATILE_SecretBase_Tire_BottomLeft             0x288
#define METATILE_SecretBase_Tire_BottomRight            0x289
#define METATILE_SecretBase_Tire_TopLeft                0x280
#define METATILE_SecretBase_Tire_TopRight               0x281
#define METATILE_SecretBase_TropicalPlant_Base1         0x2DA
#define METATILE_SecretBase_TropicalPlant_Base2         0x2DB
#define METATILE_SecretBase_TropicalPlant_Top           0x2D2
#define METATILE_SecretBase_TropicalPlant_TopWall       0x2D3
#define METATILE_SecretBase_Wall_TopMid                 0x202
#define METATILE_SecretBase_YellowBalloon               0x340
#define METATILE_SecretBase_YellowBrick_Bottom          0x22E
#define METATILE_SecretBase_YellowBrick_Top             0x226

// gTileset_Snowrie
#define METATILE_Snowrie_Snow                       0x200
#define METATILE_Snowrie_Snow_TreeLeft              0x202
#define METATILE_Snowrie_Snow_TreeRight             0x203
#define METATILE_Snowrie_TallGrass_Clear            0x209
#define METATILE_Snowrie_TallGrass_Clear_TreeLeft   0x20E
#define METATILE_Snowrie_TallGrass_Clear_TreeRight  0x20F
#define METATILE_Snowrie_TallGrass_Snowy            0x201
#define METATILE_Snowrie_TallGrass_Snowy_TreeLeft   0x206
#define METATILE_Snowrie_TallGrass_Snowy_TreeRight  0x207

// Other
#define METATILE_SilphCo_ElevatorDoor            0x2E2
#define METATILE_SilphCo_ElevatorWindow_Bottom0  0x2F8
#define METATILE_SilphCo_ElevatorWindow_Bottom1  0x2F9
#define METATILE_SilphCo_ElevatorWindow_Bottom2  0x2FA
#define METATILE_SilphCo_ElevatorWindow_Mid0     0x2F0
#define METATILE_SilphCo_ElevatorWindow_Mid1     0x2F1
#define METATILE_SilphCo_ElevatorWindow_Mid2     0x2F2
#define METATILE_SilphCo_ElevatorWindow_Top0     0x2E8
#define METATILE_SilphCo_ElevatorWindow_Top1     0x2E9
#define METATILE_SilphCo_ElevatorWindow_Top2     0x2EA

#endif // GUARD_METATILE_LABELS_H
