MountBriar_Lodge_MapScripts::
	.byte 0


MountBriar_Lodge_Talk_Man1::
# 4 "data/maps/MountBriar_Lodge/scripts.pory"
	lock
# 5 "data/maps/MountBriar_Lodge/scripts.pory"
	faceplayer
# 6 "data/maps/MountBriar_Lodge/scripts.pory"
	msgbox MountBriar_Lodge_Talk_Man1_Text_0, MSGBOX_DEFAULT
# 10 "data/maps/MountBriar_Lodge/scripts.pory"
	closemessage
# 11 "data/maps/MountBriar_Lodge/scripts.pory"
	release
	return


MountBriar_Lodge_Talk_Man2::
# 15 "data/maps/MountBriar_Lodge/scripts.pory"
	lock
# 16 "data/maps/MountBriar_Lodge/scripts.pory"
	faceplayer
# 17 "data/maps/MountBriar_Lodge/scripts.pory"
	msgbox MountBriar_Lodge_Talk_Man1_Text_0, MSGBOX_DEFAULT
# 21 "data/maps/MountBriar_Lodge/scripts.pory"
	closemessage
# 22 "data/maps/MountBriar_Lodge/scripts.pory"
	release
	return


MountBriar_Lodge_Talk_Woman1::
# 26 "data/maps/MountBriar_Lodge/scripts.pory"
	lock
# 27 "data/maps/MountBriar_Lodge/scripts.pory"
	faceplayer
# 28 "data/maps/MountBriar_Lodge/scripts.pory"
	msgbox MountBriar_Lodge_Talk_Man1_Text_0, MSGBOX_DEFAULT
# 32 "data/maps/MountBriar_Lodge/scripts.pory"
	closemessage
# 33 "data/maps/MountBriar_Lodge/scripts.pory"
	release
	return


MountBriar_Lodge_Talk_Woman2::
# 37 "data/maps/MountBriar_Lodge/scripts.pory"
	lock
# 38 "data/maps/MountBriar_Lodge/scripts.pory"
	faceplayer
# 39 "data/maps/MountBriar_Lodge/scripts.pory"
	msgbox MountBriar_Lodge_Talk_Man1_Text_0, MSGBOX_DEFAULT
# 43 "data/maps/MountBriar_Lodge/scripts.pory"
	closemessage
# 44 "data/maps/MountBriar_Lodge/scripts.pory"
	release
	return


MountBriar_Lodge_Talk_Cashier::
# 48 "data/maps/MountBriar_Lodge/scripts.pory"
	lock
# 49 "data/maps/MountBriar_Lodge/scripts.pory"
	faceplayer
# 50 "data/maps/MountBriar_Lodge/scripts.pory"
	msgbox MountBriar_Lodge_Talk_Man1_Text_0, MSGBOX_DEFAULT
# 54 "data/maps/MountBriar_Lodge/scripts.pory"
	closemessage
# 55 "data/maps/MountBriar_Lodge/scripts.pory"
	release
	return


MountBriar_Lodge_Talk_Man1_Text_0:
# 7 "data/maps/MountBriar_Lodge/scripts.pory"
	.string "TODO$"
