LittlerootTown_BrendansHouse_2F_EventScript_PC::
	end

LittlerootTown_MaysHouse_2F_EventScript_PC::
	end

LittlerootTown_BrendansHouse_2F_EventScript_TurnOffPlayerPC::
	end

LittlerootTown_MaysHouse_2F_EventScript_TurnOffPlayerPC::
	end

LittlerootTown_ProfessorBirchsLab_EventScript_ScottAboardSSTidalCall::
	end

Ferry_EventScript_DepartIslandSouth::
	end

Ferry_EventScript_DepartIslandWest::
	end

SSTidalCorridor_EventScript_ReachedStepCount::
	end

MossdeepCity_SpaceCenter_2F_EventScript_ChoosePartyForMultiBattle::
	end

MossdeepCity_SpaceCenter_2F_EventScript_RivalRayquazaCall::
	end

MauvilleCity_EventScript_RegisterWallyCall::
	end

MauvilleCity_GameCorner_EventScript_NoCoinCase::
	end

RustboroCity_Gym_EventScript_RegisterRoxanne::
	end

EventScript_ClosedSootopolisDoor::
	end

EventScript_RegisterProfBirch::
	end

SkyPillar_Outside_EventScript_ClosedDoor::
	end

IslandCave_EventScript_OpenRegiEntrance::
	end

FarawayIsland_Interior_EventScript_HideMewWhenGrassCut::
	end

Route110_TrickHousePuzzle_EventScript_Door::
	end

Route119_EventScript_ScottWonAtFortreeGymCall::
	end

BattleFrontier_OutsideEast_EventScript_WaterSudowoodo::
	end

BattleFrontier_BattlePike_EventScript_CloseCurtain::
	end

BattleFrontier_BattlePyramid_EventScript_WarpToLobbyLost::
	end

BattlePyramid_TrainerBattle::
	end

BattlePyramid_FindItemBall::
	end

BattlePyramid_WarpToNextFloor::
	end

BattlePyramid_Retire::
	end

